# Generated by Django 5.1.2 on 2024-10-12 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_options_rename_assigned_to_task_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='member',
            new_name='assigned_to',
        ),
    ]
