# Generated by Django 5.1.2 on 2024-10-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-due_date']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='assigned_to',
            new_name='member',
        ),
    ]
